# Generated by Django 5.2.12 on 2026-03-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, choices=[('bourg', 'Le Bourg'), ('souverand', 'Souverand'), ('zanieres', 'Zanières'), ('pessade', 'Pessade'), ('la_martre', 'La Martre'), ('espinasse', 'Espinasse')], help_text='Village ou hameau de résidence à Saulzet-le-Froid.', max_length=20, verbose_name='village'),
        ),
    ]
