# Generated by Django 5.2.12 on 2026-03-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='function_order',
            field=models.PositiveIntegerField(default=100, help_text='Ordre sur la page équipe (1 = Maire, 2 = 1er Adjoint, etc.)', verbose_name="ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='user',
            name='function_title',
            field=models.CharField(blank=True, help_text='Ex: Maire, 1er Adjoint, Conseiller municipal', max_length=100, verbose_name='fonction'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo pour la page équipe municipale.', null=True, upload_to='accounts/photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('secretary', 'Secrétaire de mairie'), ('mayor', 'Maire / 1er Adjoint'), ('elected', 'Adjoint / Conseiller'), ('citizen', 'Habitant')], default='citizen', max_length=10, verbose_name='rôle'),
        ),
    ]
