# Generated by Django 5.2.12 on 2026-03-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Saulzet & Vous', max_length=100, verbose_name='Nom du site')),
                ('commune_name', models.CharField(default='Saulzet-le-Froid', max_length=100, verbose_name='Nom de la commune')),
                ('population', models.CharField(default='284 habitants', help_text="Affiché sur la page d'accueil et la page commune.", max_length=50, verbose_name='Population')),
                ('address', models.CharField(default='Le Bourg, 63710 Saulzet-le-Froid', max_length=200, verbose_name='Adresse')),
                ('phone', models.CharField(default='04 73 22 81 65', max_length=20, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, default='', help_text='Optionnel. Affiché sur la carte et la page contact.', max_length=20, verbose_name='Téléphone secondaire')),
                ('opening_hours', models.TextField(default='Lundi, mardi, jeudi et vendredi\n8h30 — 12h00', help_text="Une ligne par information. Affiché sur l'accueil et la page contact.", verbose_name="Horaires d'ouverture")),
                ('email_from_name', models.CharField(default='Saulzet & Vous', help_text='Nom affiché dans le champ « De » des emails envoyés.', max_length=100, verbose_name="Nom de l'expéditeur")),
                ('email_from_address', models.EmailField(default='noreply@saulzet-le-froid.com', help_text='Adresse email utilisée comme expéditeur pour tous les emails du site.', max_length=254, verbose_name="Adresse email d'expédition")),
                ('email_contact', models.EmailField(default='mairie@saulzet-le-froid.com', help_text='Adresse où arrivent les messages du formulaire de contact.', max_length=254, verbose_name='Email de contact (mairie)')),
                ('smtp_host', models.CharField(blank=True, default='', help_text='Ex : smtp.brevo.com, smtp.gmail.com. Laisser vide pour utiliser la console (dev).', max_length=200, verbose_name='Serveur SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='587 pour TLS (recommandé), 465 pour SSL, 25 pour non chiffré.', verbose_name='Port SMTP')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=200, verbose_name='Identifiant SMTP')),
                ('smtp_password', models.CharField(blank=True, default='', help_text="Stocké en clair en base. Utiliser une clé API plutôt qu'un mot de passe personnel.", max_length=200, verbose_name='Mot de passe SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Activer pour le port 587 (recommandé). Désactiver pour le port 465 (SSL).', verbose_name='Utiliser TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Activer uniquement pour le port 465.', verbose_name='Utiliser SSL')),
                ('map_center_lat', models.FloatField(default=45.6415, verbose_name='Latitude centre carte')),
                ('map_center_lng', models.FloatField(default=2.91, verbose_name='Longitude centre carte')),
                ('map_default_zoom', models.PositiveSmallIntegerField(default=13, verbose_name='Zoom par défaut')),
                ('mairie_lat', models.FloatField(default=45.6415, verbose_name='Latitude mairie')),
                ('mairie_lng', models.FloatField(default=2.9178, verbose_name='Longitude mairie')),
                ('orphan_days', models.PositiveIntegerField(default=7, help_text="Nombre de jours avant qu'une sollicitation non affectée soit signalée en relance.", verbose_name='Seuil sollicitations orphelines (jours)')),
                ('cleanup_days', models.PositiveIntegerField(default=30, help_text='Nombre de jours par défaut pour la suppression des sollicitations résolues/annulées.', verbose_name='Seuil nettoyage (jours)')),
                ('stats_period_days', models.PositiveIntegerField(default=180, help_text='Nombre de jours affichés dans les graphiques du tableau de bord maire.', verbose_name='Période statistiques (jours)')),
                ('reminder_interval_days', models.PositiveIntegerField(default=7, help_text='Nombre de jours minimum entre deux relances pour la même sollicitation.', verbose_name='Intervalle entre relances (jours)')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['order', 'name'],
            },
        ),
    ]
