# Generated by Django 5.2.12 on 2026-03-27 12:42

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(help_text="Identifiant dans l'URL. Généré automatiquement depuis le titre.", max_length=200, unique=True, verbose_name='slug')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='contenu')),
                ('excerpt', models.TextField(blank=True, help_text='Court résumé affiché dans les listes et les accès rapides.', verbose_name='résumé')),
                ('menu_order', models.PositiveIntegerField(default=0, help_text='Les pages sont triées par ce nombre (croissant).', verbose_name='ordre dans le menu')),
                ('is_published', models.BooleanField(default=True, verbose_name='publiée')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='afficher dans le menu')),
                ('template', models.CharField(choices=[('default', 'Standard'), ('full_width', 'Pleine largeur'), ('contact', 'Page de contact'), ('documents', 'Liste de documents'), ('equipe', 'Équipe municipale')], default='default', max_length=20, verbose_name='gabarit')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='description SEO')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/images/', verbose_name="image d'en-tête")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('parent', models.ForeignKey(blank=True, help_text='Laisser vide pour une page de premier niveau.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page', verbose_name='page parente')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_updated', to=settings.AUTH_USER_MODEL, verbose_name='modifiée par')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('file', models.FileField(upload_to='documents/', verbose_name='fichier')),
                ('category', models.CharField(choices=[('pv', 'Procès-verbal de conseil'), ('bulletin', 'Bulletin municipal'), ('plu', 'Document PLU'), ('arrete', 'Arrêté'), ('other', 'Autre')], default='other', max_length=20, verbose_name='catégorie')),
                ('date', models.DateField(blank=True, help_text='Date du document (ex: date du conseil municipal).', null=True, verbose_name='date du document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploadé le')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploadé par')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='pages.page', verbose_name='page associée')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-date', '-uploaded_at'],
            },
        ),
    ]
