# Generated by Django 5.2.12 on 2026-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', 'Standard'), ('full_width', 'Pleine largeur'), ('contact', 'Page de contact'), ('documents', 'Liste de documents'), ('equipe', 'Équipe municipale'), ('habitants', 'Habitants'), ('acces', 'Accès et plan')], default='default', max_length=20, verbose_name='gabarit'),
        ),
    ]
