# Generated by Django 5.2.12 on 2026-03-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', 'Standard'), ('full_width', 'Pleine largeur'), ('contact', 'Page de contact'), ('documents', 'Liste de documents'), ('equipe', 'Équipe municipale'), ('habitants', 'Habitants'), ('acces', 'Accès et plan'), ('galerie', 'Galerie photos')], default='default', max_length=20, verbose_name='gabarit'),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/%Y/%m/', verbose_name='image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/thumbnails/%Y/%m/', verbose_name='miniature')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('credit', models.CharField(blank=True, help_text='Nom du photographe ou source.', max_length=200, verbose_name='crédits photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='publiée')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='pages.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'photo de galerie',
                'verbose_name_plural': 'photos de galerie',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
