# Generated by Django 5.2.12 on 2026-03-22 14:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('report_type', models.CharField(choices=[('question', 'Question'), ('idea', 'Idee / Suggestion'), ('issue', 'Signalement')], default='issue', max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('assigned', 'Pris en charge'), ('in_progress', 'En cours'), ('resolved', 'Resolu'), ('cancelled', 'Annule')], default='new', max_length=15, verbose_name='statut')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('location_text', models.CharField(blank=True, max_length=255, verbose_name='description du lieu')),
                ('resolution_text', models.TextField(blank=True, verbose_name='texte de resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'assignation")),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='date de resolution')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='assigne par')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='assigne a')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'sollicitation',
                'verbose_name_plural': 'sollicitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reports/photos/%Y/%m/', verbose_name='image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='reports/thumbnails/%Y/%m/', verbose_name='miniature')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nom du fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'upload")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.report', verbose_name='sollicitation')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='contenu')),
                ('is_status_change', models.BooleanField(default=False, verbose_name='changement de statut')),
                ('old_status', models.CharField(blank=True, max_length=15, null=True, verbose_name='ancien statut')),
                ('new_status', models.CharField(blank=True, max_length=15, null=True, verbose_name='nouveau statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report', verbose_name='sollicitation')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['created_at'],
            },
        ),
    ]
