# Generated by Django 5.2.12 on 2026-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si activé, la sollicitation est visible par tous les habitants.', verbose_name='sollicitation publique'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('question', 'Question'), ('idea', 'Idée / Suggestion'), ('issue', 'Signalement')], default='issue', max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('assigned', 'Pris en charge'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('cancelled', 'Annulé')], default='new', max_length=15, verbose_name='statut'),
        ),
    ]
